[tool.isort]
profile="black"
skip_gitignore=true

[tool.mypy]
strict=true
files = [
    "lta",
    "tests"
]

[[tool.mypy.overrides]]
module = [
    'firebase_admin.*',
    'google.*',
    'vonage'
]
ignore_missing_imports = true

[tool.pytest.ini_options]
testpaths = [
    "tests",
]